import type { EventType } from "@/lib/types";

/**
 * Tipos de evento por marca. El público (audience) es lo que habilita o
 * bloquea servicios: una celebración de 15 o de 18 es "with-minors" aunque sea
 * de noche, y nunca puede recibir ofertas exclusivas para adultos.
 *
 * Lo exclusivo para mayores no está acá: vive en adultos.ts y solo lo carga
 * la ruta /noche-magik/mayores (ver catalog.ts).
 */
export const eventTypes: EventType[] = [
  // ---------- Daale · particulares ----------
  {
    id: "daale-cumple-infantil",
    brand: "daale",
    clientType: "particular",
    label: "Cumpleaños infantil",
    description: "Personajes, juegos y estética para los chicos.",
    audience: "with-minors",
    isBusiness: false,
    asksAgeMix: true,
    order: 10,
  },
  {
    id: "daale-cumple-adultos",
    brand: "daale",
    clientType: "particular",
    label: "Cumpleaños de adultos",
    description: "Una sorpresa con personajes para alguien grande.",
    audience: "adults",
    isBusiness: false,
    asksAgeMix: false,
    order: 20,
  },
  {
    id: "daale-familiar",
    brand: "daale",
    clientType: "particular",
    label: "Celebración familiar",
    description: "Bautismo, comunión, baby shower o una reunión especial.",
    audience: "all-ages",
    isBusiness: false,
    asksAgeMix: true,
    order: 30,
  },
  {
    id: "daale-otro-particular",
    brand: "daale",
    clientType: "particular",
    label: "Otra celebración",
    description: "Contanos qué tenés en mente.",
    audience: "all-ages",
    isBusiness: false,
    asksAgeMix: true,
    isOther: true,
    order: 40,
  },

  // ---------- Daale · empresas e instituciones ----------
  {
    id: "daale-shopping",
    brand: "daale",
    clientType: "empresa",
    label: "Shopping o centro comercial",
    description: "Ciclos de fin de semana, fechas especiales y activaciones.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    order: 50,
  },
  {
    id: "daale-cine",
    brand: "daale",
    clientType: "empresa",
    label: "Cine o estreno",
    description: "Recepción con personajes en estrenos y funciones.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    order: 60,
  },
  {
    id: "daale-comercio",
    brand: "daale",
    clientType: "empresa",
    label: "Comercio o local",
    description: "Aperturas, promociones y días especiales.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    order: 70,
  },
  {
    id: "daale-marca",
    brand: "daale",
    clientType: "empresa",
    label: "Activación de marca",
    description: "Presencia de marca con personajes o muñeco mascota.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    order: 80,
  },
  {
    id: "daale-corporativo",
    brand: "daale",
    clientType: "empresa",
    label: "Evento corporativo",
    description: "Día de la familia, fin de año o evento interno.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    order: 90,
  },
  {
    id: "daale-institucion",
    brand: "daale",
    clientType: "empresa",
    label: "Escuela, jardín o institución",
    description: "Efemérides, fechas patrias y actos.",
    audience: "with-minors",
    isBusiness: true,
    asksAgeMix: false,
    order: 100,
  },
  {
    id: "daale-otro-empresa",
    brand: "daale",
    clientType: "empresa",
    label: "Otra acción",
    description: "Contanos qué necesitás.",
    audience: "all-ages",
    isBusiness: true,
    asksAgeMix: false,
    isOther: true,
    order: 110,
  },

  // ---------- Noche Magik · celebraciones ----------
  {
    id: "nm-15",
    brand: "noche-magik",
    clientType: "particular",
    label: "Celebración de 15",
    description: "Entrada, recepción y show para la noche de 15.",
    audience: "with-minors",
    isBusiness: false,
    asksAgeMix: false,
    order: 10,
  },
  {
    id: "nm-18",
    brand: "noche-magik",
    clientType: "particular",
    label: "Celebración de 18",
    description: "Una fiesta de 18 con show y animación.",
    audience: "with-minors",
    isBusiness: false,
    asksAgeMix: false,
    order: 20,
  },
  {
    id: "nm-casamiento",
    brand: "noche-magik",
    clientType: "particular",
    label: "Casamiento",
    description: "Recepción de invitados y show para la fiesta.",
    audience: "all-ages",
    isBusiness: false,
    asksAgeMix: false,
    order: 30,
  },
  {
    id: "nm-fiesta",
    brand: "noche-magik",
    clientType: "particular",
    label: "Fiesta o celebración",
    description: "Aniversario, cumpleaños o fiesta privada.",
    audience: "adults",
    isBusiness: false,
    asksAgeMix: false,
    order: 40,
  },
  {
    id: "nm-boliche",
    brand: "noche-magik",
    clientType: "empresa",
    label: "Boliche o fiesta temática",
    description: "Performers, personajes y animación para la pista.",
    audience: "adults",
    isBusiness: true,
    asksAgeMix: false,
    order: 50,
  },
  {
    id: "nm-show",
    brand: "noche-magik",
    clientType: "particular",
    label: "Show para un evento",
    description: "Un número especial para un momento de la noche.",
    audience: "all-ages",
    isBusiness: false,
    asksAgeMix: false,
    order: 60,
  },
  {
    id: "nm-empresa",
    brand: "noche-magik",
    clientType: "empresa",
    label: "Evento de empresa",
    description: "Fin de año, lanzamiento o evento corporativo de noche.",
    audience: "adults",
    isBusiness: true,
    asksAgeMix: false,
    order: 70,
  },
  {
    id: "nm-otro",
    brand: "noche-magik",
    clientType: "particular",
    label: "Otro evento",
    description: "Contanos qué tenés en mente.",
    audience: "all-ages",
    isBusiness: false,
    asksAgeMix: false,
    isOther: true,
    order: 80,
  },
];
