import type { Service } from "@/lib/types";

/**
 * Catálogo por marca. pendingConfirmation marca lo que no aparece en ningún
 * material de la marca (tríptico, propuestas comerciales, mensajes a clientes)
 * y hay que validar antes de publicar.
 *
 * Lo exclusivo para mayores no está acá: vive en adultos.ts y solo lo carga
 * la ruta /noche-magik/mayores (ver catalog.ts). Las reglas de público viven
 * en lib/audience.ts y no dependen de este orden.
 */
export const serviceCategories: Record<string, string> = {
  // Daale
  personajes: "Personajes y show",
  estetica: "Estética y juegos",
  deco: "Deco y extras",
  empresas: "Para empresas y marcas",
  // Noche Magik
  recepcion: "Recepción",
  shows: "Shows y artistas",
  animacion: "Animación para la fiesta",
  ambientacion: "Ambientación y producción",
};

export const services: Service[] = [
  // ---------- Daale · Personajes y show ----------
  {
    id: "daale-personajes",
    slug: "personajes",
    brand: "daale",
    name: "Personajes",
    shortDescription:
      "Personajes en vivo para fotos, juegos y el momento de la torta.",
    category: "personajes",
    image: "daale-personaje",
    audience: "all-ages",
    tags: ["fotos", "cumpleaños"],
    pairsWith: ["daale-animacion", "daale-maquillaje", "daale-fotos"],
    durationHint: "1 a 2 horas",
    commercialPriority: 1,
    price: null,
    pendingConfirmation: false,
    opensCharacters: true,
  },
  {
    id: "daale-animacion",
    slug: "animacion",
    brand: "daale",
    name: "Animación y juegos",
    shortDescription:
      "Juegos adaptados al lugar, a las edades y a la cantidad de chicos.",
    category: "personajes",
    image: "daale-animacion",
    audience: "all-ages",
    tags: ["juegos"],
    pairsWith: ["daale-personajes", "daale-globoflexia"],
    durationHint: "1 a 2 horas",
    commercialPriority: 2,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-titeres",
    slug: "titeres",
    brand: "daale",
    name: "Obra de títeres",
    shortDescription: "Una obra temática para que los chicos se sienten a mirar.",
    category: "personajes",
    image: "daale-titeres",
    audience: "all-ages",
    tags: ["show"],
    pairsWith: ["daale-animacion"],
    commercialPriority: 6,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-estatuas",
    slug: "estatuas-vivientes",
    brand: "daale",
    name: "Estatuas vivientes",
    shortDescription:
      "Personajes quietos que cobran vida y sorprenden a los invitados.",
    category: "personajes",
    audience: "all-ages",
    tags: ["recepción", "sorpresa"],
    pairsWith: ["daale-recepcion"],
    commercialPriority: 9,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-mimo",
    slug: "mimo",
    brand: "daale",
    name: "Mimo",
    shortDescription: "Un mimo para la entrada, las fotos y los momentos de juego.",
    category: "personajes",
    audience: "all-ages",
    tags: ["recepción"],
    pairsWith: ["daale-recepcion"],
    commercialPriority: 12,
    price: null,
    pendingConfirmation: true,
  },
  {
    id: "daale-zancudo",
    slug: "zancudo",
    brand: "daale",
    name: "Zancudo",
    shortDescription: "Un artista en zancos que se ve desde todo el lugar.",
    category: "personajes",
    audience: "all-ages",
    tags: ["recepción", "empresas"],
    pairsWith: ["daale-recepcion"],
    commercialPriority: 13,
    price: null,
    pendingConfirmation: true,
  },

  // ---------- Daale · Estética y juegos ----------
  {
    id: "daale-maquillaje",
    slug: "maquillaje-artistico",
    brand: "daale",
    name: "Maquillaje artístico",
    shortDescription: "Caritas pintadas con temas para cada edad.",
    category: "estetica",
    image: "daale-maquillaje",
    audience: "all-ages",
    tags: ["estética"],
    pairsWith: ["daale-glitter", "daale-peinados"],
    commercialPriority: 3,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-glitter",
    slug: "glitter-y-tattoos",
    brand: "daale",
    name: "Glitter y tattoos",
    shortDescription: "Brillos, tatuajes al agua y stencils temáticos.",
    category: "estetica",
    audience: "all-ages",
    tags: ["estética"],
    pairsWith: ["daale-maquillaje"],
    commercialPriority: 4,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-peinados",
    slug: "trenzas-y-peinados",
    brand: "daale",
    name: "Trenzas y peinados locos",
    shortDescription: "Trenzas fluo, mechitas de color y peinados locos.",
    category: "estetica",
    audience: "all-ages",
    tags: ["estética"],
    pairsWith: ["daale-maquillaje"],
    commercialPriority: 7,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-globoflexia",
    slug: "globoflexia",
    brand: "daale",
    name: "Globoflexia",
    shortDescription: "Figuras con globos para que cada uno se lleve de regalo.",
    category: "estetica",
    image: "daale-globoflexia",
    audience: "all-ages",
    tags: ["regalo"],
    pairsWith: ["daale-animacion"],
    commercialPriority: 5,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-sector-creativo",
    slug: "sector-creativo",
    brand: "daale",
    name: "Sector creativo",
    shortDescription:
      "Mesas con láminas temáticas para colorear y juegos guiados.",
    category: "estetica",
    audience: "all-ages",
    tags: ["empresas", "shopping"],
    pairsWith: ["daale-maquillaje"],
    commercialPriority: 10,
    price: null,
    pendingConfirmation: false,
  },

  // ---------- Daale · Deco y extras ----------
  {
    id: "daale-deco",
    slug: "decoracion",
    brand: "daale",
    name: "Decoración y ambientación",
    shortDescription: "Deco temática para el salón o el espacio del evento.",
    category: "deco",
    image: "daale-deco",
    audience: "all-ages",
    tags: ["deco"],
    pairsWith: ["daale-cotillon", "daale-fotos"],
    commercialPriority: 8,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-cotillon",
    slug: "cotillon-artesanal",
    brand: "daale",
    name: "Cotillón artesanal",
    shortDescription: "Cotillón personalizado y exclusivo, hecho a mano.",
    category: "deco",
    audience: "all-ages",
    tags: ["deco"],
    pairsWith: ["daale-deco"],
    commercialPriority: 11,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-cascada",
    slug: "cascada-de-chocolate",
    brand: "daale",
    name: "Cascada de chocolate",
    shortDescription: "Para la mesa dulce, con frutas y golosinas para bañar.",
    category: "deco",
    image: "daale-cascada",
    audience: "all-ages",
    tags: ["mesa dulce"],
    pairsWith: ["daale-deco"],
    commercialPriority: 14,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-recepcion",
    slug: "recepcion",
    brand: "daale",
    name: "Recepción con personajes",
    shortDescription: "Personajes que reciben a los invitados en la entrada.",
    category: "deco",
    audience: "all-ages",
    tags: ["recepción", "empresas"],
    pairsWith: ["daale-personajes"],
    commercialPriority: 15,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "daale-fotos",
    slug: "rincon-de-fotos",
    brand: "daale",
    name: "Rincón de fotos",
    shortDescription: "Un espacio armado para sacarse fotos con los personajes.",
    category: "deco",
    audience: "all-ages",
    tags: ["fotos"],
    pairsWith: ["daale-personajes", "daale-deco"],
    commercialPriority: 16,
    price: null,
    pendingConfirmation: true,
  },
  {
    id: "daale-desayuno",
    slug: "desayuno-sorpresa",
    brand: "daale",
    name: "Desayuno sorpresa",
    shortDescription:
      "Un personaje lleva el desayuno o la merienda a quien quieras sorprender.",
    category: "deco",
    audience: "all-ages",
    tags: ["regalo", "sorpresa"],
    pairsWith: [],
    commercialPriority: 17,
    price: null,
    pendingConfirmation: false,
    clientTypes: ["particular"],
  },

  // ---------- Daale · Para empresas y marcas ----------
  {
    id: "daale-intervencion",
    slug: "intervencion-tematica",
    brand: "daale",
    name: "Intervención temática",
    shortDescription:
      "Una puesta con personajes pensada para el espacio y la fecha.",
    category: "empresas",
    image: "daale-empresas",
    audience: "all-ages",
    tags: ["empresas", "shopping"],
    pairsWith: ["daale-recepcion", "daale-sector-creativo"],
    commercialPriority: 18,
    price: null,
    pendingConfirmation: true,
    clientTypes: ["empresa"],
  },
  {
    id: "daale-mascota",
    slug: "muneco-mascota",
    brand: "daale",
    name: "Muñeco mascota de marca",
    shortDescription:
      "Confección y animación de un muñeco mascota para tu marca.",
    category: "empresas",
    audience: "all-ages",
    tags: ["empresas", "marca"],
    pairsWith: ["daale-recepcion"],
    commercialPriority: 19,
    price: null,
    pendingConfirmation: false,
    clientTypes: ["empresa"],
  },
  {
    id: "daale-produccion",
    slug: "produccion-personalizada",
    brand: "daale",
    name: "Producción personalizada",
    shortDescription: "Una propuesta a medida para el objetivo de la acción.",
    category: "empresas",
    audience: "all-ages",
    tags: ["empresas"],
    pairsWith: [],
    commercialPriority: 20,
    price: null,
    pendingConfirmation: true,
    clientTypes: ["empresa"],
  },

  // ---------- Noche Magik · Recepción ----------
  {
    id: "nm-recepcion",
    slug: "recepcion",
    brand: "noche-magik",
    name: "Recepción de invitados",
    shortDescription:
      "Artistas que reciben a los invitados y marcan el comienzo de la noche.",
    category: "recepcion",
    image: "nm-recepcion",
    audience: "all-ages",
    tags: ["recepción"],
    pairsWith: ["nm-zancudos", "nm-mimos"],
    commercialPriority: 1,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "nm-mimos",
    slug: "mimos-y-pierrot",
    brand: "noche-magik",
    name: "Mimos y pierrot",
    shortDescription: "Personajes clásicos para la entrada y las fotos.",
    category: "recepcion",
    audience: "all-ages",
    tags: ["recepción"],
    pairsWith: ["nm-recepcion"],
    commercialPriority: 4,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "nm-zancudos",
    slug: "zancudos",
    brand: "noche-magik",
    name: "Zancudos",
    shortDescription:
      "Artistas en zancos para una entrada que se ve desde todo el salón.",
    category: "recepcion",
    image: "nm-zancudos",
    audience: "all-ages",
    tags: ["recepción", "entrada"],
    pairsWith: ["nm-recepcion"],
    commercialPriority: 3,
    price: null,
    pendingConfirmation: false,
  },

  // ---------- Noche Magik · Shows y artistas ----------
  {
    id: "nm-hombre-espejo",
    slug: "hombre-espejo",
    brand: "noche-magik",
    name: "Hombre espejo",
    shortDescription:
      "Un performer cubierto de espejos que refleja las luces de la fiesta.",
    category: "shows",
    image: "nm-hombre-espejo",
    audience: "all-ages",
    tags: ["show", "fotos"],
    pairsWith: ["nm-recepcion", "nm-performers"],
    commercialPriority: 2,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "nm-performers",
    slug: "performers-de-pista",
    brand: "noche-magik",
    name: "Performers de pista",
    shortDescription: "Artistas en el escenario o la tarima, con humo y luces.",
    category: "shows",
    image: "nm-performers",
    audience: "all-ages",
    tags: ["show", "boliche"],
    pairsWith: ["nm-animacion"],
    commercialPriority: 5,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "nm-personajes",
    slug: "personajes-de-peliculas",
    brand: "noche-magik",
    name: "Personajes de películas",
    shortDescription: "Personajes para las fotos y los momentos de la fiesta.",
    category: "shows",
    image: "nm-personajes",
    audience: "all-ages",
    tags: ["fotos"],
    pairsWith: ["nm-animacion"],
    commercialPriority: 6,
    price: null,
    pendingConfirmation: false,
    opensCharacters: true,
  },
  {
    id: "nm-show-tematico",
    slug: "show-tematico",
    brand: "noche-magik",
    name: "Show temático",
    shortDescription:
      "Una noche con temática: terror, disfraces o la que elijas.",
    category: "shows",
    image: "nm-tematico",
    audience: "all-ages",
    tags: ["show", "temática"],
    pairsWith: ["nm-ambientacion"],
    commercialPriority: 8,
    price: null,
    pendingConfirmation: false,
  },

  // ---------- Noche Magik · Animación para la fiesta ----------
  {
    id: "nm-animacion",
    slug: "animacion-nocturna",
    brand: "noche-magik",
    name: "Animación durante la noche",
    shortDescription:
      "Juegos, momentos y energía para sostener la fiesta hasta el final.",
    category: "animacion",
    audience: "all-ages",
    tags: ["animación"],
    pairsWith: ["nm-performers"],
    commercialPriority: 7,
    price: null,
    pendingConfirmation: false,
  },
  {
    id: "nm-pasacalle",
    slug: "pasacalle-artesanal",
    brand: "noche-magik",
    name: "Pasacalle artesanal",
    shortDescription:
      "Un pasacalle hecho a mano con el nombre o la frase que elijas.",
    category: "animacion",
    audience: "all-ages",
    tags: ["regalo", "sorpresa"],
    pairsWith: [],
    commercialPriority: 9,
    price: null,
    pendingConfirmation: false,
  },

  // ---------- Noche Magik · Ambientación y producción ----------
  {
    id: "nm-ambientacion",
    slug: "ambientacion-nocturna",
    brand: "noche-magik",
    name: "Ambientación nocturna",
    shortDescription: "Deco y luces para darle identidad a la noche.",
    category: "ambientacion",
    image: "nm-ambientacion",
    audience: "all-ages",
    tags: ["deco"],
    pairsWith: ["nm-show-tematico"],
    commercialPriority: 10,
    price: null,
    pendingConfirmation: true,
  },
  {
    id: "nm-produccion",
    slug: "produccion-especial",
    brand: "noche-magik",
    name: "Producción especial",
    shortDescription: "Una propuesta a medida para un momento único de la noche.",
    category: "ambientacion",
    audience: "all-ages",
    tags: ["empresas"],
    pairsWith: [],
    commercialPriority: 11,
    price: null,
    pendingConfirmation: true,
  },
];
